//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnviaSeFaz.RetAutorizacaoRJ {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetAutorizacao", ConfigurationName="RetAutorizacaoRJ.NfeRetAutorizacaoSoap12")]
    public interface NfeRetAutorizacaoSoap12 {
        
        // CODEGEN: Generating message contract since the operation nfeRetAutorizacaoLote is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetAutorizacao/nfeRetAutorizacaoLote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EnviaSeFaz.RetAutorizacaoRJ.nfeRetAutorizacaoLoteResponse nfeRetAutorizacaoLote(EnviaSeFaz.RetAutorizacaoRJ.nfeRetAutorizacaoLoteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetAutorizacao")]
    public partial class nfeCabecMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cUFField;
        
        private string versaoDadosField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string cUF {
            get {
                return this.cUFField;
            }
            set {
                this.cUFField = value;
                this.RaisePropertyChanged("cUF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string versaoDados {
            get {
                return this.versaoDadosField;
            }
            set {
                this.versaoDadosField = value;
                this.RaisePropertyChanged("versaoDados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeRetAutorizacaoLoteRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetAutorizacao")]
        public EnviaSeFaz.RetAutorizacaoRJ.nfeCabecMsg nfeCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetAutorizacao", Order=0)]
        public System.Xml.XmlNode nfeDadosMsg;
        
        public nfeRetAutorizacaoLoteRequest() {
        }
        
        public nfeRetAutorizacaoLoteRequest(EnviaSeFaz.RetAutorizacaoRJ.nfeCabecMsg nfeCabecMsg, System.Xml.XmlNode nfeDadosMsg) {
            this.nfeCabecMsg = nfeCabecMsg;
            this.nfeDadosMsg = nfeDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeRetAutorizacaoLoteResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetAutorizacao")]
        public EnviaSeFaz.RetAutorizacaoRJ.nfeCabecMsg nfeCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetAutorizacao", Order=0)]
        public System.Xml.XmlNode nfeRetAutorizacaoLoteResult;
        
        public nfeRetAutorizacaoLoteResponse() {
        }
        
        public nfeRetAutorizacaoLoteResponse(EnviaSeFaz.RetAutorizacaoRJ.nfeCabecMsg nfeCabecMsg, System.Xml.XmlNode nfeRetAutorizacaoLoteResult) {
            this.nfeCabecMsg = nfeCabecMsg;
            this.nfeRetAutorizacaoLoteResult = nfeRetAutorizacaoLoteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NfeRetAutorizacaoSoap12Channel : EnviaSeFaz.RetAutorizacaoRJ.NfeRetAutorizacaoSoap12, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NfeRetAutorizacaoSoap12Client : System.ServiceModel.ClientBase<EnviaSeFaz.RetAutorizacaoRJ.NfeRetAutorizacaoSoap12>, EnviaSeFaz.RetAutorizacaoRJ.NfeRetAutorizacaoSoap12 {
        
        public NfeRetAutorizacaoSoap12Client() {
        }
        
        public NfeRetAutorizacaoSoap12Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NfeRetAutorizacaoSoap12Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NfeRetAutorizacaoSoap12Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NfeRetAutorizacaoSoap12Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EnviaSeFaz.RetAutorizacaoRJ.nfeRetAutorizacaoLoteResponse EnviaSeFaz.RetAutorizacaoRJ.NfeRetAutorizacaoSoap12.nfeRetAutorizacaoLote(EnviaSeFaz.RetAutorizacaoRJ.nfeRetAutorizacaoLoteRequest request) {
            return base.Channel.nfeRetAutorizacaoLote(request);
        }
        
        public System.Xml.XmlNode nfeRetAutorizacaoLote(ref EnviaSeFaz.RetAutorizacaoRJ.nfeCabecMsg nfeCabecMsg, System.Xml.XmlNode nfeDadosMsg) {
            EnviaSeFaz.RetAutorizacaoRJ.nfeRetAutorizacaoLoteRequest inValue = new EnviaSeFaz.RetAutorizacaoRJ.nfeRetAutorizacaoLoteRequest();
            inValue.nfeCabecMsg = nfeCabecMsg;
            inValue.nfeDadosMsg = nfeDadosMsg;
            EnviaSeFaz.RetAutorizacaoRJ.nfeRetAutorizacaoLoteResponse retVal = ((EnviaSeFaz.RetAutorizacaoRJ.NfeRetAutorizacaoSoap12)(this)).nfeRetAutorizacaoLote(inValue);
            nfeCabecMsg = retVal.nfeCabecMsg;
            return retVal.nfeRetAutorizacaoLoteResult;
        }
    }
}
