//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnviaSeFaz.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.sefaz.mt.gov.br/nfcews/services/NfeAutorizacao")]
        public string EnviaSeFaz_br_gov_mt_sefaz_homologacao_NfeAutorizacao {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_mt_sefaz_homologacao_NfeAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.sefaz.mt.gov.br/nfcews/services/NfeRetAutorizacao")]
        public string EnviaSeFaz_br_gov_mt_sefaz_homologacao1_NfeRetAutorizacao {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_mt_sefaz_homologacao1_NfeRetAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.sefaz.mt.gov.br/nfcews/services/NfeStatusServico2")]
        public string EnviaSeFaz_br_gov_mt_sefaz_homologacao2_NfeStatusServico2 {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_mt_sefaz_homologacao2_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefaz.mt.gov.br/nfcews/services/NfeAutorizacao")]
        public string EnviaSeFaz_br_gov_mt_sefaz_nfce_NfeAutorizacao {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_mt_sefaz_nfce_NfeAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefaz.mt.gov.br/nfcews/services/NfeRetAutorizacao")]
        public string EnviaSeFaz_br_gov_mt_sefaz_nfce1_NfeRetAutorizacao {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_mt_sefaz_nfce1_NfeRetAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefaz.mt.gov.br/nfcews/services/NfeStatusServico2")]
        public string EnviaSeFaz_br_gov_mt_sefaz_nfce2_NfeStatusServico2 {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_mt_sefaz_nfce2_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefaz.am.gov.br/nfce-services/services/NfeAutorizacao")]
        public string EnviaSeFaz_br_gov_am_sefaz_nfce_NfeAutorizacao {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_am_sefaz_nfce_NfeAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefaz.am.gov.br/nfce-services/services/NfeRetAutorizacao")]
        public string EnviaSeFaz_br_gov_am_sefaz_nfce1_NfeRetAutorizacao {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_am_sefaz_nfce1_NfeRetAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefaz.am.gov.br/nfce-services/services/NfeStatusServico2")]
        public string EnviaSeFaz_br_gov_am_sefaz_nfce2_NfeStatusServico2 {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_am_sefaz_nfce2_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefaz.am.gov.br/nfce-services/services/NfeAutorizacao")]
        public string EnviaSeFaz_br_gov_am_sefaz_homnfce_NfeAutorizacao {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_am_sefaz_homnfce_NfeAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefaz.am.gov.br/nfce-services/services/NfeRetAutorizacao")]
        public string EnviaSeFaz_br_gov_am_sefaz_homnfce1_NfeRetAutorizacao {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_am_sefaz_homnfce1_NfeRetAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefaz.am.gov.br/nfce-services/services/NfeStatusServico2")]
        public string EnviaSeFaz_br_gov_am_sefaz_homnfce2_NfeStatusServico2 {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_am_sefaz_homnfce2_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefazvirtual.rs.gov.br/ws/NfeStatusServico/NfeStatusServico2.asmx")]
        public string EnviaSeFaz_br_gov_rs_sefazvirtual_nfe_NfeStatusServico2 {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_sefazvirtual_nfe_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/NfeConsulta/NfeConsulta2.asmx")]
        public string EnviaSeFaz_br_gov_rs_sefazvirtual_nfe_homologacao_NfeConsulta2 {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_sefazvirtual_nfe_homologacao_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/NfeStatusServico/NfeStatusServi" +
            "co2.asmx")]
        public string EnviaSeFaz_br_gov_rs_sefazvirtual_nfe_homologacao1_NfeStatusServico2 {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_sefazvirtual_nfe_homologacao1_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao.a" +
            "smx")]
        public string EnviaSeFaz_br_gov_rs_sefazvirtual_nfe_homologacao2_NfeAutorizacao {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_sefazvirtual_nfe_homologacao2_NfeAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutoriz" +
            "acao.asmx")]
        public string EnviaSeFaz_br_gov_rs_sefazvirtual_nfe_homologacao3_NfeRetAutorizacao {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_sefazvirtual_nfe_homologacao3_NfeRetAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefazvirtual.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao.asmx")]
        public string EnviaSeFaz_br_gov_rs_sefazvirtual_nfe1_NfeAutorizacao {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_sefazvirtual_nfe1_NfeAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefazvirtual.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao.asmx")]
        public string EnviaSeFaz_br_gov_rs_sefazvirtual_nfe2_NfeRetAutorizacao {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_sefazvirtual_nfe2_NfeRetAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.svc.fazenda.gov.br/RecepcaoEvento/RecepcaoEvento.asmx")]
        public string EnviaSeFaz_br_gov_fazenda_svc_hom_RecepcaoEvento {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_fazenda_svc_hom_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.sefaz.mt.gov.br/nfcews/services/RecepcaoEvento")]
        public string EnviaSeFaz_br_gov_mt_sefaz_homologacao3_RecepcaoEvento {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_mt_sefaz_homologacao3_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.svc.fazenda.gov.br/NfeStatusServico2/NfeStatusServico2.asmx")]
        public string EnviaSeFaz_br_gov_fazenda_svc_hom1_NfeStatusServico2 {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_fazenda_svc_hom1_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.svc.fazenda.gov.br/NfeStatusServico2/NfeStatusServico2.asmx")]
        public string EnviaSeFaz_br_gov_fazenda_svc_www_NfeStatusServico2 {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_fazenda_svc_www_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.svc.fazenda.gov.br/NfeAutorizacao/NfeAutorizacao.asmx")]
        public string EnviaSeFaz_br_gov_fazenda_svc_hom2_NfeAutorizacao {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_fazenda_svc_hom2_NfeAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.svc.fazenda.gov.br/NfeAutorizacao/NfeAutorizacao.asmx")]
        public string EnviaSeFaz_br_gov_fazenda_svc_www1_NfeAutorizacao {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_fazenda_svc_www1_NfeAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.svc.fazenda.gov.br/NfeRetAutorizacao/NfeRetAutorizacao.asmx")]
        public string EnviaSeFaz_br_gov_fazenda_svc_hom3_NfeRetAutorizacao {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_fazenda_svc_hom3_NfeRetAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.svc.fazenda.gov.br/NfeRetAutorizacao/NfeRetAutorizacao.asmx")]
        public string EnviaSeFaz_br_gov_fazenda_svc_www2_NfeRetAutorizacao {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_fazenda_svc_www2_NfeRetAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefaz.rs.gov.br/ws/NfeStatusServico/NfeStatusServico2.asm" +
            "x")]
        public string EnviaSeFaz_br_gov_rs_sefaz_nfe_homologacao_NfeStatusServico2 {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_sefaz_nfe_homologacao_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.rs.gov.br/ws/NfeStatusServico/NfeStatusServico2.asmx")]
        public string EnviaSeFaz_br_gov_rs_sefaz_nfe_NfeStatusServico2 {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_sefaz_nfe_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefaz.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao.asmx")]
        public string EnviaSeFaz_br_gov_rs_sefaz_nfe_homologacao1_NfeAutorizacao {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_sefaz_nfe_homologacao1_NfeAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao.asmx")]
        public string EnviaSeFaz_br_gov_rs_sefaz_nfe1_NfeAutorizacao {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_sefaz_nfe1_NfeAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefaz.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao.as" +
            "mx")]
        public string EnviaSeFaz_br_gov_rs_sefaz_nfe_homologacao2_NfeRetAutorizacao {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_sefaz_nfe_homologacao2_NfeRetAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao.asmx")]
        public string EnviaSeFaz_br_gov_rs_sefaz_nfe2_NfeRetAutorizacao {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_sefaz_nfe2_NfeRetAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefaz.rs.gov.br/ws/recepcaoevento/recepcaoevento.asmx")]
        public string EnviaSeFaz_br_gov_rs_sefaz_nfe_homologacao3_RecepcaoEvento {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_sefaz_nfe_homologacao3_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.rs.gov.br/ws/recepcaoevento/recepcaoevento.asmx")]
        public string EnviaSeFaz_br_gov_rs_sefaz_nfe3_RecepcaoEvento {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_sefaz_nfe3_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefaz.mt.gov.br/nfcews/services/RecepcaoEvento")]
        public string EnviaSeFaz_br_gov_mt_sefaz_nfce3_RecepcaoEvento {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_mt_sefaz_nfce3_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.rs.gov.br/ws/NfeInutilizacao/NfeInutilizacao2.asmx")]
        public string EnviaSeFaz_br_gov_rs_sefaz_nfe4_NfeInutilizacao2 {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_sefaz_nfe4_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefaz.rs.gov.br/ws/NfeInutilizacao/NfeInutilizacao2.asmx")]
        public string EnviaSeFaz_br_gov_rs_sefaz_nfe_homologacao4_NfeInutilizacao2 {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_sefaz_nfe_homologacao4_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao" +
            "2.asmx")]
        public string EnviaSeFaz_br_gov_rs_sefazvirtual_nfe_homologacao4_NfeInutilizacao2 {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_sefazvirtual_nfe_homologacao4_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefazvirtual.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao2.asmx")]
        public string EnviaSeFaz_br_gov_rs_sefazvirtual_nfe3_NfeInutilizacao2 {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_sefazvirtual_nfe3_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.sefaz.mt.gov.br/nfcews/services/NfeInutilizacao2")]
        public string EnviaSeFaz_br_gov_mt_sefaz_homologacao4_NfeInutilizacao2 {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_mt_sefaz_homologacao4_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefaz.mt.gov.br/nfcews/services/NfeInutilizacao2")]
        public string EnviaSeFaz_br_gov_mt_sefaz_nfce4_NfeInutilizacao2 {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_mt_sefaz_nfce4_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://homnfce.sefaz.am.gov.br/nfce-services-nac/services/RecepcaoEvento")]
        public string EnviaSeFaz_br_gov_am_sefaz_homnfce3_RecepcaoEvento {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_am_sefaz_homnfce3_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefaz.am.gov.br/nfce-services/services/NfeRecepcao2")]
        public string EnviaSeFaz_br_gov_am_sefaz_nfce3_NfeRecepcao2 {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_am_sefaz_nfce3_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefaz.am.gov.br/nfce-services/services/RecepcaoEvento")]
        public string EnviaSeFaz_br_gov_am_sefaz_nfce4_RecepcaoEvento {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_am_sefaz_nfce4_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homnfce.sefaz.am.gov.br/nfce-services/services/NfeInutilizacao2")]
        public string EnviaSeFaz_br_gov_am_sefaz_homnfce4_NfeInutilizacao2 {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_am_sefaz_homnfce4_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefaz.am.gov.br/nfce-services/services/NfeInutilizacao2")]
        public string EnviaSeFaz_br_gov_am_sefaz_nfce5_NfeInutilizacao2 {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_am_sefaz_nfce5_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefazvirtual.rs.gov.br/ws/recepcaoevento/recepcaoevento.asmx")]
        public string EnviaSeFaz_br_gov_rs_sefazvirtual_nfe4_RecepcaoEvento {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_sefazvirtual_nfe4_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/recepcaoevento/recepcaoevento.a" +
            "smx")]
        public string EnviaSeFaz_br_gov_rs_sefazvirtual_nfe_homologacao5_RecepcaoEvento {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_sefazvirtual_nfe_homologacao5_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce-homologacao.sefazrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao.asmx")]
        public string EnviaSeFaz_br_gov_rs_sefazrs_nfcehomologacao_NfeAutorizacao {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_sefazrs_nfcehomologacao_NfeAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce-homologacao.sefazrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico2." +
            "asmx")]
        public string EnviaSeFaz_br_gov_rs_sefazrs_nfcehomologacaoStatuts_NfeStatusServico2 {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_sefazrs_nfcehomologacaoStatuts_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce-homologacao.sefazrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao" +
            ".asmx")]
        public string EnviaSeFaz_br_gov_rs_sefazrs_nfcehomologacaoRet_NfeRetAutorizacao {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_sefazrs_nfcehomologacaoRet_NfeRetAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce-homologacao.sefazrs.rs.gov.br/ws/recepcaoevento/recepcaoevento.asmx")]
        public string EnviaSeFaz_br_gov_rs_sefazrs_nfcehomologacaoRecepcao_RecepcaoEvento {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_sefazrs_nfcehomologacaoRecepcao_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce-homologacao.sefazrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao2.as" +
            "mx")]
        public string EnviaSeFaz_br_gov_rs_sefazrs_nfcehomologacaoInutilizacao_NfeInutilizacao2 {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_sefazrs_nfcehomologacaoInutilizacao_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefazrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico2.asmx")]
        public string EnviaSeFaz_br_gov_rs_sefazrs_nfceStatus_NfeStatusServico2 {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_sefazrs_nfceStatus_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefazrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao.asmx")]
        public string EnviaSeFaz_br_gov_rs_sefazrs_nfceAut_NfeAutorizacao {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_sefazrs_nfceAut_NfeAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefazrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao.asmx")]
        public string EnviaSeFaz_br_gov_rs_sefazrs_nfceRet_NfeRetAutorizacao {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_sefazrs_nfceRet_NfeRetAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefazrs.rs.gov.br/ws/recepcaoevento/recepcaoevento.asmx")]
        public string EnviaSeFaz_br_gov_rs_sefazrs_nfceEvento_RecepcaoEvento {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_sefazrs_nfceEvento_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefazrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao2.asmx")]
        public string EnviaSeFaz_br_gov_rs_sefazrs_nfceInutilizacao_NfeInutilizacao2 {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_sefazrs_nfceInutilizacao_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico2.asm" +
            "x")]
        public string EnviaSeFaz_br_gov_rs_svrs_nfcehomologacaoStatus_NfeStatusServico2 {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_svrs_nfcehomologacaoStatus_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao.asmx")]
        public string EnviaSeFaz_br_gov_rs_svrs_nfcehomologacaoAut_NfeAutorizacao {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_svrs_nfcehomologacaoAut_NfeAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao.as" +
            "mx")]
        public string EnviaSeFaz_br_gov_rs_svrs_nfcehomologacaoRet_NfeRetAutorizacao {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_svrs_nfcehomologacaoRet_NfeRetAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento.asmx")]
        public string EnviaSeFaz_br_gov_rs_svrs_nfcehomologacaoRec_RecepcaoEvento {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_svrs_nfcehomologacaoRec_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao2.asmx")]
        public string EnviaSeFaz_br_gov_rs_svrs_nfcehomologacaoInut_NfeInutilizacao2 {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_svrs_nfcehomologacaoInut_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico2.asmx")]
        public string EnviaSeFaz_br_gov_rs_svrs_nfceStatus_NfeStatusServico2 {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_svrs_nfceStatus_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao.asmx")]
        public string EnviaSeFaz_br_gov_rs_svrs_nfceAuto_NfeAutorizacao {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_svrs_nfceAuto_NfeAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao.asmx")]
        public string EnviaSeFaz_br_gov_rs_svrs_nfceRet_NfeRetAutorizacao {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_svrs_nfceRet_NfeRetAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento.asmx")]
        public string EnviaSeFaz_br_gov_rs_svrs_nfceEvento_RecepcaoEvento {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_svrs_nfceEvento_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao2.asmx")]
        public string EnviaSeFaz_br_gov_rs_svrs_nfceInut_NfeInutilizacao2 {
            get {
                return ((string)(this["EnviaSeFaz_br_gov_rs_svrs_nfceInut_NfeInutilizacao2"]));
            }
        }
    }
}
