//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatServerAppContingencia.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefaz.mt.gov.br/nfcews/services/NfeAutorizacao")]
        public string SatServerAppContigencia_br_gov_mt_sefaz_nfce_NfeAutorizacao {
            get {
                return ((string)(this["SatServerAppContigencia_br_gov_mt_sefaz_nfce_NfeAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefaz.mt.gov.br/nfcews/services/NfeRetAutorizacao")]
        public string SatServerAppContigencia_br_gov_mt_sefaz_nfce1_NfeRetAutorizacao {
            get {
                return ((string)(this["SatServerAppContigencia_br_gov_mt_sefaz_nfce1_NfeRetAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefaz.mt.gov.br/nfcews/services/NfeStatusServico2")]
        public string SatServerAppContigencia_br_gov_mt_sefaz_nfce2_NfeStatusServico2 {
            get {
                return ((string)(this["SatServerAppContigencia_br_gov_mt_sefaz_nfce2_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefaz.am.gov.br/nfce-services/services/NfeConsulta2")]
        public string SatServerAppContigencia_br_gov_am_sefaz_nfce_NfeConsulta2 {
            get {
                return ((string)(this["SatServerAppContigencia_br_gov_am_sefaz_nfce_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefaz.am.gov.br/nfce-services/services/NfeAutorizacao")]
        public string SatServerAppContigencia_br_gov_am_sefaz_nfce1_NfeAutorizacao {
            get {
                return ((string)(this["SatServerAppContigencia_br_gov_am_sefaz_nfce1_NfeAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefaz.am.gov.br/nfce-services/services/NfeRetAutorizacao")]
        public string SatServerAppContigencia_br_gov_am_sefaz_nfce2_NfeRetAutorizacao {
            get {
                return ((string)(this["SatServerAppContigencia_br_gov_am_sefaz_nfce2_NfeRetAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefaz.am.gov.br/nfce-services/services/NfeStatusServico2")]
        public string SatServerAppContigencia_br_gov_am_sefaz_nfce3_NfeStatusServico2 {
            get {
                return ((string)(this["SatServerAppContigencia_br_gov_am_sefaz_nfce3_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.sefaz.mt.gov.br/nfcews/services/NfeStatusServico2")]
        public string SatServerAppContigencia_br_gov_mt_sefaz_homologacao_NfeStatusServico2 {
            get {
                return ((string)(this["SatServerAppContigencia_br_gov_mt_sefaz_homologacao_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.sefaz.mt.gov.br/nfcews/services/NfeAutorizacao")]
        public string SatServerAppContigencia_br_gov_mt_sefaz_homologacao1_NfeAutorizacao {
            get {
                return ((string)(this["SatServerAppContigencia_br_gov_mt_sefaz_homologacao1_NfeAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.sefaz.mt.gov.br/nfcews/services/NfeRetAutorizacao")]
        public string SatServerAppContigencia_br_gov_mt_sefaz_homologacao2_NfeRetAutorizacao {
            get {
                return ((string)(this["SatServerAppContigencia_br_gov_mt_sefaz_homologacao2_NfeRetAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.am.gov.br/services2/services/NfeAutorizacao")]
        public string SatServerAppContigencia_br_gov_am_sefaz_homnfe_NfeAutorizacao {
            get {
                return ((string)(this["SatServerAppContigencia_br_gov_am_sefaz_homnfe_NfeAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.am.gov.br/services2/services/NfeRetAutorizacao")]
        public string SatServerAppContigencia_br_gov_am_sefaz_homnfe1_NfeRetAutorizacao {
            get {
                return ((string)(this["SatServerAppContigencia_br_gov_am_sefaz_homnfe1_NfeRetAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.sefaz.am.gov.br/services2/services/NfeStatusServico2")]
        public string SatServerAppContigencia_br_gov_am_sefaz_homnfe2_NfeStatusServico2 {
            get {
                return ((string)(this["SatServerAppContigencia_br_gov_am_sefaz_homnfe2_NfeStatusServico2"]));
            }
        }
    }
}
