//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.34014
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class CFe {
    
    private CFeInfCFe infCFeField;


    private Signature SignatureField;

    public Signature Signature
    {
        get
        {
            return this.SignatureField;
        }
        set
        {
            this.SignatureField = value;
        }
    }


    /// <remarks/>
    public CFeInfCFe infCFe {
        get {
            return this.infCFeField;
        }
        set {
            this.infCFeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CFeInfCFe {
    
    private CFeInfCFeIde ideField;
    
    private CFeInfCFeEmit emitField;
    
    private string destField;
    
    private CFeInfCFeDet detField;
    
    private CFeInfCFetotal totalField;


    private string IdField;

    private CFeInfCFePgto pgtoField;
    
    private float versaoDadosEntField;
    
    private bool versaoDadosEntFieldSpecified;
    
    /// <remarks/>
    public CFeInfCFeIde ide {
        get {
            return this.ideField;
        }
        set {
            this.ideField = value;
        }
    }
    
    /// <remarks/>
    public CFeInfCFeEmit emit {
        get {
            return this.emitField;
        }
        set {
            this.emitField = value;
        }
    }
    
    /// <remarks/>
    public string dest {
        get {
            return this.destField;
        }
        set {
            this.destField = value;
        }
    }
    
    /// <remarks/>
    public CFeInfCFeDet det {
        get {
            return this.detField;
        }
        set {
            this.detField = value;
        }
    }
    
    /// <remarks/>
    public CFeInfCFetotal total
    {
        get {
            return this.totalField;
        }
        set {
            this.totalField = value;
        }
    }
    
    /// <remarks/>
    public CFeInfCFePgto pgto {
        get {
            return this.pgtoField;
        }
        set {
            this.pgtoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float versaoDadosEnt {
        get {
            return this.versaoDadosEntField;
        }
        set {
            this.versaoDadosEntField = value;
        }
    }

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id{
        get {
            return this.IdField;
        }
        set {
            this.IdField = value;
        }
    }

    



    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool versaoDadosEntSpecified {
        get {
            return this.versaoDadosEntFieldSpecified;
        }
        set {
            this.versaoDadosEntFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CFeInfCFeIde {
    
    private string cNPJField;
    
    private string signACField;

    private string UFFields;
    private string NFFields;
    private string modFields;
    private string nserieSATFields;
    private string nCFeFields;
    private string dEmiFields;
    private string cDVFields;
    private string hEmiFields;
    private sbyte numeroCaixaField;
    private string assinaturaQRCODEFilds;

  
    
    public string hEmi
    {
        get
        {
            return this.hEmiFields;
        }
        set
        {
            this.hEmiFields = value;
        }
    }
    public string cDV
    {
        get
        {
            return this.cDVFields;
        }
        set
        {
            this.cDVFields = value;
        }
    }


    public string dEmi
    {
        get
        {
            return this.dEmiFields;
        }
        set
        {
            this.dEmiFields = value;
        }
    }

    public string nCFe
    {
        get
        {
            return this.nCFeFields;
        }
        set
        {
            this.nCFeFields = value;
        }
    }


    public string nserieSAT
    {
        get
        {
            return this.nserieSATFields;
        }
        set
        {
            this.nserieSATFields = value;
        }
    }

    public string CNPJ {
        get {
            return this.cNPJField;
        }
        set {
            this.cNPJField = value;
        }
    }

    public string cUF
    {
        get
        {
            return this.UFFields;
        }
        set
        {
            this.UFFields = value;
        }
    }

    public string mod
    {
        get
        {
            return this.modFields;
        }
        set
        {
            this.modFields = value;
        }
    }

   
    public string cNF
    {
        get
        {
            return this.NFFields;
        }
        set
        {
            this.NFFields = value;
        }
    }

    public string assinaturaQRCODE
    {
        get
        {
            return this.assinaturaQRCODEFilds;
        }
        set
        {
            this.assinaturaQRCODEFilds = value;
        }
    }



    /// <remarks/>
    public string signAC {
        get {
            return this.signACField;
        }
        set {
            this.signACField = value;
        }
    }
    
    /// <remarks/>
    public sbyte numeroCaixa {
        get {
            return this.numeroCaixaField;
        }
        set {
            this.numeroCaixaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CFeInfCFeEmit {
    
    private string cNPJField;
    
    private string ieField;
    
    private string imField;
    
    private string indRatISSQNField;

    private string xNomeField;

    private string xFantField;

    private string cRegTribField;


    private CFeInfCFeenderEmit enderEmitField;

    /// <remarks/>
    public CFeInfCFeenderEmit enderEmit
    {
        get
        {
            return this.enderEmitField;
        }
        set
        {
            this.enderEmitField = value;
        }
    }

    public string cRegTrib
    {
        get
        {
            return this.cRegTribField;
        }
        set
        {
            this.cRegTribField = value;
        }
    }

    public string xNome
    {
        get
        {
            return this.xNomeField;
        }
        set
        {
            this.xNomeField = value;
        }
    }

    public string xFant
    {
        get
        {
            return this.xFantField;
        }
        set
        {
            this.xFantField = value;
        }
    }


    /// <remarks/>
    public string CNPJ {
        get {
            return this.cNPJField;
        }
        set {
            this.cNPJField = value;
        }
    }
    
    /// <remarks/>
    public string IE {
        get {
            return this.ieField;
        }
        set {
            this.ieField = value;
        }
    }
    
    /// <remarks/>
    public string IM {
        get {
            return this.imField;
        }
        set {
            this.imField = value;
        }
    }
    
    /// <remarks/>
    public string indRatISSQN {
        get {
            return this.indRatISSQNField;
        }
        set {
            this.indRatISSQNField = value;
        }
    }
}



[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class CFeInfCFepgto
{
    private string vTrocoField;
    private CFeInfCFeMP MPfield;
    
    public string vTroco
    {
        get
        {
            return this.vTrocoField;
        }
        set
        {
            this.vTrocoField = value;
        }
    }

    public CFeInfCFeMP MP
    {
        get
        {
            return this.MPfield;
        }
        set
        {
            this.MPfield = value;
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class CFeInfCFeMP
{
    private string cMPField;
    private string vMPField;
    public string cMP
    {
        get
        {
            return this.cMPField;
        }
        set
        {
            this.cMPField = value;
        }
    }
    public string vMP
    {
        get
        {
            return this.vMPField;
        }
        set
        {
            this.vMPField = value;
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class CFeInfCFetotal
{
    private string vCFeField;
    private CFeInfCFeICMSTotal ICMSTotField;
    
    public string vCFe
    {
        get
        {
            return this.vCFeField;
        }
        set
        {
            this.vCFeField = value;
        }
    }

    public CFeInfCFeICMSTotal ICMSTot
    {
        get
        {
            return this.ICMSTotField;
        }
        set
        {
            this.ICMSTotField = value;
        }
    }

}
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class CFeInfCFeICMSTotal
{
    private string vICMSField;
    private string vProdField;
    private string vDescField;
    private string vPISField;
    private string vCOFINSField;
    private string vPISSTField;
    private string vCOFINSSTField;
    private string vOutroField;


    public string vOutro
    {
        get
        {
            return this.vOutroField;
        }
        set
        {
            this.vOutroField = value;
        }
    }

    public string vCOFINSST
    {
        get
        {
            return this.vCOFINSSTField;
        }
        set
        {
            this.vCOFINSSTField = value;
        }
    }

    public string vPISST
    {
        get
        {
            return this.vPISSTField;
        }
        set
        {
            this.vPISSTField = value;
        }
    }

    public string vCOFINS
    {
        get
        {
            return this.vCOFINSField;
        }
        set
        {
            this.vCOFINSField = value;
        }
    }

    public string vPIS
    {
        get
        {
            return this.vPISField;
        }
        set
        {
            this.vPISField = value;
        }
    }

    public string vDesc
    {
        get
        {
            return this.vDescField;
        }
        set
        {
            this.vDescField = value;
        }
    }

    public string vProd
    {
        get
        {
            return this.vProdField;
        }
        set
        {
            this.vProdField = value;
        }
    }

    public string vICMS
    {
        get
        {
            return this.vICMSField;
        }
        set
        {
            this.vICMSField = value;
        }
    }

}
         

[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class CFeInfCFeenderEmit
{
    private string xLgrField;
    private string nroField;
    private string xCplField;
    private string xBairroField;
    private string xMunField;
    private string CEPField;

    public string CEP
    {
        get
        {
            return this.CEPField;
        }
        set
        {
            this.CEPField = value;
        }
    }
    public string xMun
    {
        get
        {
            return this.xMunField;
        }
        set
        {
            this.xMunField = value;
        }
    }
    public string xBairro
    {
        get
        {
            return this.xBairroField;
        }
        set
        {
            this.xBairroField = value;
        }
    }

    public string xCpl
    {
        get
        {
            return this.xCplField;
        }
        set
        {
            this.xCplField = value;
        }
    }

    public string nro
    {
        get
        {
            return this.nroField;
        }
        set
        {
            this.nroField = value;
        }
    }

    public string xLgr
    {
        get
        {
            return this.xLgrField;
        }
        set
        {
            this.xLgrField = value;
        }
    }

}



/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CFeInfCFeDet {
    
    private object[] itemsField;
    
    private sbyte nItemField;
    
    private bool nItemFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("imposto", typeof(CFeInfCFeDetImposto))]
    [System.Xml.Serialization.XmlElementAttribute("prod", typeof(CFeInfCFeDetProd))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte nItem {
        get {
            return this.nItemField;
        }
        set {
            this.nItemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool nItemSpecified {
        get {
            return this.nItemFieldSpecified;
        }
        set {
            this.nItemFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CFeInfCFeDetImposto {
    
    private CFeInfCFeDetImpostoICMS iCMSField;
    
    private CFeInfCFeDetImpostoPIS pISField;
    
    private CFeInfCFeDetImpostoPISST pISSTField;
    
    private CFeInfCFeDetImpostoCOFINS cOFINSField;
    
    private CFeInfCFeDetImpostoCOFINSST cOFINSSTField;
    
    private sbyte cProdField;
    
    private bool cProdFieldSpecified;
    
    private string xProdField;
    
    private sbyte cFOPField;
    
    private bool cFOPFieldSpecified;
    
    private string uComField;
    
    private float qComField;
    
    private bool qComFieldSpecified;
    
    private float vUnComField;
    
    private bool vUnComFieldSpecified;
    
    private string indRegraField;
    
    /// <remarks/>
    public CFeInfCFeDetImpostoICMS ICMS {
        get {
            return this.iCMSField;
        }
        set {
            this.iCMSField = value;
        }
    }
    
    /// <remarks/>
    public CFeInfCFeDetImpostoPIS PIS {
        get {
            return this.pISField;
        }
        set {
            this.pISField = value;
        }
    }
    
    /// <remarks/>
    public CFeInfCFeDetImpostoPISST PISST {
        get {
            return this.pISSTField;
        }
        set {
            this.pISSTField = value;
        }
    }
    
    /// <remarks/>
    public CFeInfCFeDetImpostoCOFINS COFINS {
        get {
            return this.cOFINSField;
        }
        set {
            this.cOFINSField = value;
        }
    }
    
    /// <remarks/>
    public CFeInfCFeDetImpostoCOFINSST COFINSST {
        get {
            return this.cOFINSSTField;
        }
        set {
            this.cOFINSSTField = value;
        }
    }
    
    /// <remarks/>
    public sbyte cProd {
        get {
            return this.cProdField;
        }
        set {
            this.cProdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool cProdSpecified {
        get {
            return this.cProdFieldSpecified;
        }
        set {
            this.cProdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string xProd {
        get {
            return this.xProdField;
        }
        set {
            this.xProdField = value;
        }
    }
    
    /// <remarks/>
    public sbyte CFOP {
        get {
            return this.cFOPField;
        }
        set {
            this.cFOPField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CFOPSpecified {
        get {
            return this.cFOPFieldSpecified;
        }
        set {
            this.cFOPFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string uCom {
        get {
            return this.uComField;
        }
        set {
            this.uComField = value;
        }
    }
    
    /// <remarks/>
    public float qCom {
        get {
            return this.qComField;
        }
        set {
            this.qComField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool qComSpecified {
        get {
            return this.qComFieldSpecified;
        }
        set {
            this.qComFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public float vUnCom {
        get {
            return this.vUnComField;
        }
        set {
            this.vUnComField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool vUnComSpecified {
        get {
            return this.vUnComFieldSpecified;
        }
        set {
            this.vUnComFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string indRegra {
        get {
            return this.indRegraField;
        }
        set {
            this.indRegraField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CFeInfCFeDetImpostoICMS {
    
    private CFeInfCFeDetImpostoICMSICMS00 iCMS00Field;
    
    /// <remarks/>
    public CFeInfCFeDetImpostoICMSICMS00 ICMS00 {
        get {
            return this.iCMS00Field;
        }
        set {
            this.iCMS00Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CFeInfCFeDetImpostoICMSICMS00 {
    
    private sbyte origField;
    
    private sbyte cSTField;
    
    private float pICMSField;
    
    /// <remarks/>
    public sbyte Orig {
        get {
            return this.origField;
        }
        set {
            this.origField = value;
        }
    }
    
    /// <remarks/>
    public sbyte CST {
        get {
            return this.cSTField;
        }
        set {
            this.cSTField = value;
        }
    }
    
    /// <remarks/>
    public float pICMS {
        get {
            return this.pICMSField;
        }
        set {
            this.pICMSField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CFeInfCFeDetImpostoPIS {
    
    private CFeInfCFeDetImpostoPISPISAliq pISAliqField;
    
    /// <remarks/>
    public CFeInfCFeDetImpostoPISPISAliq PISAliq {
        get {
            return this.pISAliqField;
        }
        set {
            this.pISAliqField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CFeInfCFeDetImpostoPISPISAliq {
    
    private sbyte cSTField;
    
    private float vBCField;
    
    private float pPISField;
    
    /// <remarks/>
    public sbyte CST {
        get {
            return this.cSTField;
        }
        set {
            this.cSTField = value;
        }
    }
    
    /// <remarks/>
    public float vBC {
        get {
            return this.vBCField;
        }
        set {
            this.vBCField = value;
        }
    }
    
    /// <remarks/>
    public float pPIS {
        get {
            return this.pPISField;
        }
        set {
            this.pPISField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CFeInfCFeDetImpostoPISST {
    
    private float vBCField;
    
    private float pPISField;
    
    /// <remarks/>
    public float vBC {
        get {
            return this.vBCField;
        }
        set {
            this.vBCField = value;
        }
    }
    
    /// <remarks/>
    public float pPIS {
        get {
            return this.pPISField;
        }
        set {
            this.pPISField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CFeInfCFeDetImpostoCOFINS {
    
    private CFeInfCFeDetImpostoCOFINSCOFINSAliq cOFINSAliqField;
    
    /// <remarks/>
    public CFeInfCFeDetImpostoCOFINSCOFINSAliq COFINSAliq {
        get {
            return this.cOFINSAliqField;
        }
        set {
            this.cOFINSAliqField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CFeInfCFeDetImpostoCOFINSCOFINSAliq {
    
    private sbyte cSTField;
    
    private float vBCField;
    
    private float pCOFINSField;
    
    /// <remarks/>
    public sbyte CST {
        get {
            return this.cSTField;
        }
        set {
            this.cSTField = value;
        }
    }
    
    /// <remarks/>
    public float vBC {
        get {
            return this.vBCField;
        }
        set {
            this.vBCField = value;
        }
    }
    
    /// <remarks/>
    public float pCOFINS {
        get {
            return this.pCOFINSField;
        }
        set {
            this.pCOFINSField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CFeInfCFeDetImpostoCOFINSST {
    
    private float vBCField;
    
    private float pCOFINSField;
    
    /// <remarks/>
    public float vBC {
        get {
            return this.vBCField;
        }
        set {
            this.vBCField = value;
        }
    }
    
    /// <remarks/>
    public float pCOFINS {
        get {
            return this.pCOFINSField;
        }
        set {
            this.pCOFINSField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CFeInfCFeDetProd {
    
    private string cProdField;
    private string xProdField;
    private sbyte cFOPField;
    private string uComField;
    private string qComField;
    private string vUnComField;
    private string indRegraField;
    private string vProdField;
    private string vItemField;

    public string vProd
    {
        get
        {
            return this.vProdField;
        }
        set
        {
            this.vProdField = value;
        }
    }

    public string vItem
    {
        get
        {
            return this.vItemField;
        }
        set
        {
            this.vItemField = value;
        }
    }



    /// <remarks/>
    public string cProd {
        get {
            return this.cProdField;
        }
        set {
            this.cProdField = value;
        }
    }
    
    /// <remarks/>
    public string xProd {
        get {
            return this.xProdField;
        }
        set {
            this.xProdField = value;
        }
    }
    
    /// <remarks/>
    public sbyte CFOP {
        get {
            return this.cFOPField;
        }
        set {
            this.cFOPField = value;
        }
    }
    
    /// <remarks/>
    public string uCom {
        get {
            return this.uComField;
        }
        set {
            this.uComField = value;
        }
    }
    
    /// <remarks/>
    public string qCom {
        get {
            return this.qComField;
        }
        set {
            this.qComField = value;
        }
    }
    
    /// <remarks/>
    public string vUnCom {
        get {
            return this.vUnComField;
        }
        set {
            this.vUnComField = value;
        }
    }
    
    /// <remarks/>
    public string indRegra {
        get {
            return this.indRegraField;
        }
        set {
            this.indRegraField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CFeInfCFePgto {
    
    private CFeInfCFePgtoMP mpField;
    private string vTrocoField;

    public string vTroco
    {
        get
        {
            return this.vTrocoField;
        }
        set
        {
            this.vTrocoField = value;
        }
    }
    /// <remarks/>
    public CFeInfCFePgtoMP MP {
        get {
            return this.mpField;
        }
        set {
            this.mpField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CFeInfCFePgtoMP {
    
    private sbyte cMPField;
    
    private float vMPField;
    
    /// <remarks/>
    public sbyte cMP {
        get {
            return this.cMPField;
        }
        set {
            this.cMPField = value;
        }
    }
    
    /// <remarks/>
    public float vMP {
        get {
            return this.vMPField;
        }
        set {
            this.vMPField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class Signature
{

    private SignatureSignedInfo signedInfoField;

    private string signatureValueField;

    private SignatureKeyInfo keyInfoField;

    /// <remarks/>
    public SignatureSignedInfo SignedInfo
    {
        get
        {
            return this.signedInfoField;
        }
        set
        {
            this.signedInfoField = value;
        }
    }

    /// <remarks/>
    public string SignatureValue
    {
        get
        {
            return this.signatureValueField;
        }
        set
        {
            this.signatureValueField = value;
        }
    }

    /// <remarks/>
    public SignatureKeyInfo KeyInfo
    {
        get
        {
            return this.keyInfoField;
        }
        set
        {
            this.keyInfoField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class SignatureSignedInfo
{

    private SignatureSignedInfoCanonicalizationMethod canonicalizationMethodField;

    private SignatureSignedInfoSignatureMethod signatureMethodField;

    private SignatureSignedInfoReference referenceField;

    /// <remarks/>
    public SignatureSignedInfoCanonicalizationMethod CanonicalizationMethod
    {
        get
        {
            return this.canonicalizationMethodField;
        }
        set
        {
            this.canonicalizationMethodField = value;
        }
    }

    /// <remarks/>
    public SignatureSignedInfoSignatureMethod SignatureMethod
    {
        get
        {
            return this.signatureMethodField;
        }
        set
        {
            this.signatureMethodField = value;
        }
    }

    /// <remarks/>
    public SignatureSignedInfoReference Reference
    {
        get
        {
            return this.referenceField;
        }
        set
        {
            this.referenceField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class SignatureSignedInfoCanonicalizationMethod
{

    private string algorithmField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
    public string Algorithm
    {
        get
        {
            return this.algorithmField;
        }
        set
        {
            this.algorithmField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class SignatureSignedInfoSignatureMethod
{

    private string algorithmField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
    public string Algorithm
    {
        get
        {
            return this.algorithmField;
        }
        set
        {
            this.algorithmField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class SignatureSignedInfoReference
{

    private SignatureSignedInfoReferenceTransform[] transformsField;

    private SignatureSignedInfoReferenceDigestMethod digestMethodField;

    private string digestValueField;

    private string uRIField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable = false)]
    public SignatureSignedInfoReferenceTransform[] Transforms
    {
        get
        {
            return this.transformsField;
        }
        set
        {
            this.transformsField = value;
        }
    }

    /// <remarks/>
    public SignatureSignedInfoReferenceDigestMethod DigestMethod
    {
        get
        {
            return this.digestMethodField;
        }
        set
        {
            this.digestMethodField = value;
        }
    }

    /// <remarks/>
    public string DigestValue
    {
        get
        {
            return this.digestValueField;
        }
        set
        {
            this.digestValueField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string URI
    {
        get
        {
            return this.uRIField;
        }
        set
        {
            this.uRIField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class SignatureSignedInfoReferenceTransform
{

    private string algorithmField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
    public string Algorithm
    {
        get
        {
            return this.algorithmField;
        }
        set
        {
            this.algorithmField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class SignatureSignedInfoReferenceDigestMethod
{

    private string algorithmField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
    public string Algorithm
    {
        get
        {
            return this.algorithmField;
        }
        set
        {
            this.algorithmField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class SignatureKeyInfo
{

    private SignatureKeyInfoX509Data x509DataField;

    /// <remarks/>
    public SignatureKeyInfoX509Data X509Data
    {
        get
        {
            return this.x509DataField;
        }
        set
        {
            this.x509DataField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class SignatureKeyInfoX509Data
{

    private string x509CertificateField;

    /// <remarks/>
    public string X509Certificate
    {
        get
        {
            return this.x509CertificateField;
        }
        set
        {
            this.x509CertificateField = value;
        }
    }
}