//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace invoiceServerApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.sefaz.mt.gov.br/nfcews/services/NfeAutorizacao")]
        public string SatServerApp_br_gov_mt_sefaz_homologacao_NfeAutorizacao {
            get {
                return ((string)(this["SatServerApp_br_gov_mt_sefaz_homologacao_NfeAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.sefaz.mt.gov.br/nfcews/services/NfeRetAutorizacao")]
        public string SatServerApp_br_gov_mt_sefaz_homologacao1_NfeRetAutorizacao {
            get {
                return ((string)(this["SatServerApp_br_gov_mt_sefaz_homologacao1_NfeRetAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.sefaz.mt.gov.br/nfcews/services/NfeConsulta2")]
        public string SatServerApp_br_gov_mt_sefaz_homologacao2_NfeConsulta2 {
            get {
                return ((string)(this["SatServerApp_br_gov_mt_sefaz_homologacao2_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefaz.mt.gov.br/nfcews/services/NfeAutorizacao")]
        public string SatServerApp_br_gov_mt_sefaz_nfce_NfeAutorizacao {
            get {
                return ((string)(this["SatServerApp_br_gov_mt_sefaz_nfce_NfeAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefaz.mt.gov.br/nfcews/services/NfeRetAutorizacao")]
        public string SatServerApp_br_gov_mt_sefaz_nfce1_NfeRetAutorizacao {
            get {
                return ((string)(this["SatServerApp_br_gov_mt_sefaz_nfce1_NfeRetAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefaz.mt.gov.br/nfcews/services/NfeConsulta2")]
        public string SatServerApp_br_gov_mt_sefaz_nfce2_NfeConsulta2 {
            get {
                return ((string)(this["SatServerApp_br_gov_mt_sefaz_nfce2_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.sefaz.mt.gov.br/nfcews/services/NfeStatusServico2")]
        public string SatServerApp_br_gov_mt_sefaz_homologacao3_NfeStatusServico2 {
            get {
                return ((string)(this["SatServerApp_br_gov_mt_sefaz_homologacao3_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefaz.mt.gov.br/nfcews/services/NfeStatusServico2")]
        public string SatServerApp_br_gov_mt_sefaz_nfce3_NfeStatusServico2 {
            get {
                return ((string)(this["SatServerApp_br_gov_mt_sefaz_nfce3_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefaz.am.gov.br/nfce-services/services/NfeAutorizacao")]
        public string SatServerApp_br_gov_am_sefaz_homnfce_NfeAutorizacao {
            get {
                return ((string)(this["SatServerApp_br_gov_am_sefaz_homnfce_NfeAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefaz.am.gov.br/nfce-services/services/NfeRetAutorizacao")]
        public string SatServerApp_br_gov_am_sefaz_homnfce1_NfeRetAutorizacao {
            get {
                return ((string)(this["SatServerApp_br_gov_am_sefaz_homnfce1_NfeRetAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefaz.am.gov.br/nfce-services/services/NfeStatusServico2")]
        public string SatServerApp_br_gov_am_sefaz_homnfce2_NfeStatusServico2 {
            get {
                return ((string)(this["SatServerApp_br_gov_am_sefaz_homnfce2_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefaz.am.gov.br/nfce-services/services/NfeAutorizacao")]
        public string SatServerApp_br_gov_am_sefaz_nfce_NfeAutorizacao {
            get {
                return ((string)(this["SatServerApp_br_gov_am_sefaz_nfce_NfeAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefaz.am.gov.br/nfce-services/services/NfeRetAutorizacao")]
        public string SatServerApp_br_gov_am_sefaz_nfce1_NfeRetAutorizacao {
            get {
                return ((string)(this["SatServerApp_br_gov_am_sefaz_nfce1_NfeRetAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefaz.am.gov.br/nfce-services/services/NfeConsulta2")]
        public string SatServerApp_br_gov_am_sefaz_nfce2_NfeConsulta2 {
            get {
                return ((string)(this["SatServerApp_br_gov_am_sefaz_nfce2_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefaz.am.gov.br/nfce-services/services/NfeStatusServico2")]
        public string SatServerApp_br_gov_am_sefaz_nfce3_NfeStatusServico2 {
            get {
                return ((string)(this["SatServerApp_br_gov_am_sefaz_nfce3_NfeStatusServico2"]));
            }
        }
    }
}
